# This Ansible playbook adds packages to the
# O-RAN-SC build minion image that has Docker.
---
- import_playbook: ../common-packer/provision/docker.yaml

- hosts: all
  become_user: root
  become_method: sudo

  pre_tasks:
    - include_role: name=lfit.system-update

  tasks:
    - include_role:
        name: gantsign.golang
      vars:
        golang_version: 1.12
        ansible_become: true
