# This Ansible playbook adds packages to the
# O-RAN-SC build minion image that has Docker.
---
- import_playbook: ../common-packer/provision/docker.yaml

- hosts: all
  become_user: root
  become_method: sudo

  pre_tasks:
    - include_role: name=lfit.system-update

  tasks:
    - include_role:
        name: fubarhouse.ruby
      vars:
        ruby_version: 2.4.0
        ruby_packages:
          - rake
          - package_cloud

    - include_role:
        name: fubarhouse.golang
      vars:
        go_version: 1.12
